#!/bin/bash

# general
alias tree="tree -C"
alias ls="ls -F --color=auto"
alias l="ls"
alias ll="ls -lah"
alias lll="tree"
alias ..="cd .."
alias -- -="cd -"
alias cl="clear"
alias ZZ="exit"
alias :q="exit"
alias :Q="exit"
alias sudo="sudo "
alias filecount="find . -type f | wc -l"
function mk(){ mkdir "$@" && cd "$@"; }
function c(){ cd "$@" && ls; }
if [ -x "$(command -v pbcopy)" ]; then alias clip="pbcopy"; fi
if [ -x "$(command -v code)" ]; then alias vscode="/usr/local/bin/code"; fi

# Change "sudo su" to "sudo -Es" (experimental)
function sudo() {
  if [ $@ == 'su' ]; then
    /usr/bin/sudo -Es;
  else
    /usr/bin/sudo $@;
  fi
}

# folders 
alias code="c ~/code"
alias downloads="c ~/Downloads"
alias dls="downloads"
alias docs="c ~/Documents"
alias doc="docs"
alias ~="c ~"

# python
if [ -x "$(command -v python)" ]; then
  alias rmpyc='find . -name *.pyc -delete'
  alias py='python3'
  if [ -x "$(command -v coverage)" ]; then alias unittest="coverage run --source . -m unittest"; fi
  if [ -x "$(command -v flake8)" ]; then alias flake8="flake8 --ignore=E731,--max-complexity 10"; fi
fi

# git
if [ -x "$(command -v git)" ]; then
  if [ -x "$(command -v hub)" ]; then alias git="hub"; fi
  alias g="git"
  alias dgit="git --git-dir ~/.dotfiles/.git --work-tree=$HOME"
  alias dg="dgit"
  if [ -x "$(command -v clustergit)" ]; then alias cg="clustergit -R -d ~/code/"; fi
fi

# vim
if [ -x "$(command -v mvim)" ]; 
  then alias vim="mvim -v";
else if ! [ -x "$(command -v vim)" ]; 
  then alias vim="nano"; fi # eww!
fi
alias v="vim"
alias vimrc="v ~/.vimrc"

# other
alias sshtor="ssh -F ~/.ssh/config_tor"
alias sshkeys="ssh-keygen -l -f ~/.ssh/known_hosts"
alias aliases="v ${HOME}/.aliases && unalias -a && source ${HOME}/.aliases"
alias profile="v ${HOME}/.profile && unalias -a && source ${HOME}/.profile"
alias weather="curl -4 http://wttr.in/Galway"
alias ip="curl -4 icanhazip.com"
if [ -x "$(command -v tmux)" ]; then alias tmux="tmux -2"; fi
if [ -x "$(command -v hexdump)" ]; then alias hexdump="hexdump -C"; fi
if [ -x "$(command -v neomutt)" ]; then alias mutt="neomutt"; fi


if [ -x "$(command -v lwp-request)" ]; then
  # One of @janmoesen’s ProTip™s
  for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	  alias "${method}"="lwp-request -m '${method}'"
  done
fi

# OS specific
if [[ "$OSTYPE" == "darwin"* ]]; then
  if [ -x "$(command -v shasum)" ]; then alias sha256sum="shasum -a 256"; fi
  alias update="sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup"
  alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
  alias finder="open ."
  if open -Ra "electrum" ; then alias electrum='open -a electrum'; fi
  alias apt="brew"

elif [[ "$OSTYPE" == "linux"* ]]; then
  if [ -x "$(command -v apt)" ]; then
    alias apt="sudo apt"
    alias update="apt update && sudo apt-get -yy upgrade && sudo apt-get -yy autoremove && sudo apt-get clean"
    function brew(){ sudo apt "$@";}
  fi
fi
